### ISSUE TITLE
App crashes when changing network

### ISSUE THREAD

**Issue by Inrego** [Inrego/AbooIssueTracking#1]
Whenever network changes (for example leaving wifi to use mobile data) while a book is currently playing, the app crashes.

**Comment by Majawat** [comment]
I think it also crashes when changing cell towers too. Had a long drive on Sunday and it crashed very often.

**Comment by Inrego** [comment]
Could be. This is the highest priority issue for me to look into (as well as getting the iOS version out).

**Comment by Inrego** [comment]
I've solved this, I will send out a new update soon.

**Comment by Inrego** [comment]
Update has been pushed out, so I'm closing this issue.
