### ISSUE TITLE
App crash after selecting Plex server

### ISSUE THREAD

**Issue by b0bbyhimself** [Inrego/AbooIssueTracking#12]
During first setup of the app it asks you to select a Plex server (since I have more than one) and after that it prompts to select a media folder for audio files, I select the one titled "audiobooks" and the app crashes. I reopen the app and it crashes. I have cleared cache and data from the app within Android settings and attempt again, same result.

**Comment by Inrego** [comment]
I'm afraid it seems Android 7.x is not supported. For the next version, I've set minimum Android version to 8.0, which should prevent it from being installed on unsupported devices.
