### ISSUE TITLE
App hangs on first load

### ISSUE THREAD

**Issue by defenceplox** [Inrego/AbooIssueTracking#5]
Sign in to app, select server, select library, hangs on refresh.
https://imgur.com/a/ypSBhJN

Device: Huawei p20 pro
Android ver.: 10

Will try with a smaller library to see if that is the issue.

**Comment by Inrego** [comment]
There isn't anything on your imgur link.

Actually, I forgot that there's an issue with loading the items on the home page tab on first load, and on refresh and a few other cases. The the whole app freeze? Or can you move to the library tab and navigate there?

The app has been tested on a huge library, and is working very smoothly performance-wise.

**Comment by defenceplox** [comment]
![Screenshot_20201105_122158_com.renescott.aboo.jpg](https://user-images.githubusercontent.com/21691238/98244436-5b5f5900-1f67-11eb-9102-b4891efd721a.jpg)![Screenshot_20201105_130549_com.renescott.aboo.jpg](https://user-images.githubusercontent.com/21691238/98244639-a8dbc600-1f67-11eb-99d8-f520bc3ba083.jpg)

I've gone ahead and installed the GitHub app now.

I can move to other parts of the app, but nothing loads in library or home.

**Comment by Inrego** [comment]
Huh. I've never had the problem on the Library tab.

Any chance you could provide me access to the Plex library, just for a short while, so I can check if it's something related to the library? My Plex username is Inrego.

**Comment by Inrego** [comment]
Also, the title here says the problem is on first load. Is that correct? If you close the app and reopen, then it's working, or?

**Comment by defenceplox** [comment]
On all opens. Rebooted the server and the app multiple times to no avail. I'll get you added now

**Comment by Inrego** [comment]
Another user is experiencing the same issue. I'm debugging with him right now as well.

**Comment by Inrego** [comment]
The issue was related to missing cover. If an audiobook exists in the library without a cover, the library doesn't load. I've fixed it in my end, and will upload a new version asap.

**Comment by Inrego** [comment]
New version is pushed to Google Play, so should be available very soon.

**Comment by Inrego** [comment]
You can remove me from your library again.
