### ISSUE TITLE
Changing metadata in server side doesn't update app.

### ISSUE THREAD

**Issue by defenceplox** [Inrego/AbooIssueTracking#8]
I needed to merge together so mismatches on the server to correctly display the books, but the app won't update and has empty books in place of where the files were originally located. App restart does not fix the problem.

![Screenshot_20201105_153835_com.renescott.aboo.jpg](https://user-images.githubusercontent.com/21691238/98262352-6b823300-1f7d-11eb-9ad2-a7eb3a959d49.jpg)

**Comment by defenceplox** [comment]
It sorted itself out, just took a while

**Comment by Inrego** [comment]
Refresh of metadata happens when you pull to refresh on the library page. Or when the app is completely closed and opened again (metadata is first loaded from cache to show instantaneously, but a refresh is happening in the background).
